# Generated by Django 4.1.6 on 2023-04-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heh",
            name="cat_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="map.category",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="heh",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Текст статьи"),
        ),
        migrations.AlterField(
            model_name="heh",
            name="photo",
            field=models.ImageField(
                null=True, upload_to="photos/%Y/%m/%d/", verbose_name="Фото"
            ),
        ),
    ]
